### ISSUE TITLE
getFileData method doesn't load at all,

### ISSUE THREAD

**Issue by veereshi** [Aymkdn/FileToDataURI#4]
var Flash = {
  /* Flash.getFileData() is called after the file has been read */
  getFileData: function(base64) {
    showResult(base64)
  },
  /* getButtonLabel() permits to define another label for the "Load a file" button in the Flash version */
  getButtonLabel: function() {
    return "Load a file";
  }
};

 function showResult(b) {
  $('#file-result').text(b)
}

unable to get binary data on showresult function

below reference added to code:
swfobject.embedSWF("../Content/FileToDataURI.swf", "file-object", "200px", "90px", "10", "../Content/expressInstall.swf", {}, {}, {});//}

and below 3 files are refereed;
Content/FileToDataURI.swf
../Content/expressInstall.swf
../Scripts/swfobject.js" refered as javascript link in page

**Comment by Aymkdn** [comment]
You'll have to provide more information....

Is the demo working for you : https://aymkdn.github.io/FileToDataURI/ ?
Which browser do you use ?
Do you have a link where I can test it ?
Any other info ?

**Comment by Aymkdn** [comment]
No answer, so I'm closing it.

**Comment by veereshi** [comment]
IE8
