### ISSUE TITLE
Flash var not being loaded by swf file.

### ISSUE THREAD

**Issue by pleek91** [Aymkdn/FileToDataURI#5]
On my quest to upload base64 encoded image files in ie8&9 I came across your script. Looks promising but I'm having on issue. 

I copy and pasted your example code, downloaded FileToDataURI.swf from the repo, downloaded expressInstall.swf and swfobject.js from the google link you provided, and updated the link to all three in the example code. 

Everything works fine for browsers with FileReader but when it fallsback to flash there is an issue. The flash object is loaded and put on the page. But it seems like the Flash settings are not being used. The button is in german and after selecting a file nothing happens. Any ideas?

Here's my code

	var Flash = {
		/* Flash.getFileData() is called after the file has been read */
		getFileData: function(base64) {
			console.log(base64);
			showResult(base64)
		},
		/* getButtonLabel() permits to define another label for the "Load a file" button in the Flash version */
		getButtonLabel: function() {
			return "Load a file";
		}
	};

	// we just want to show the result into the div
	function showResult(b) {
		$('#file-result').text(b)
	}

	// check if the FileReader API exists... if not then load the Flash object
	if (typeof FileReader !== "function")
		// we use 80px by 23px, because we want the object to have the same size than the button
		swfobject.embedSWF("/js/FileToDataURI.swf", "file-object", "120px", "50px", "10", "/js/expressInstall.swf", {}, {}, {});
	else {
		// replace the <object> by an input file
		$('#file-object').replaceWith('<input type="file" id="file-object" value="Load a file" />');
		
		$('#file-object').on('change', function(e) {
			var files = e.target.files,file;

			if (!files || files.length == 0) return;
			file = files[0];

			var fileReader = new FileReader();
			
			fileReader.onload = function (e) {
				// ATTENTION: to have the same result than the Flash object we need to split
				// our result to keep only the Base64 part
				showResult(e.target.result.split(",")[1]);
				// showResult(e.target.result);

				$('#file-result').append('<img src="' + e.target.result + '" />');
			};

			fileReader.readAsDataURL(file);
		});
	}

**Comment by pleek91** [comment]
Nevermind. Of course as soon as I ask for help I figure it out. The issue was my Flash options were inside of `$(function(){});` which caused `swfobject.js` to not be able to see them. Great little plugin/script, thanks!

**Comment by Aymkdn** [comment]
Cool :-)
