### ISSUE TITLE
 Can I use FiletToDataURL.mxml to develop the commercial software?

### ISSUE THREAD

**Issue by usitaka** [Aymkdn/FileToDataURI#6]
Hi, I have one question and one request.
I'm using FiletToDataURL.mxml to develop the commercial software, which uploads users' files website. However, I found the statement, "CC BY-NC-SA 3.0" in FiletToDataURL.mxml

- Question;
  Can I use FiletToDataURL.mxml to develop the commercial software?

- Request
In case that your answer is "Yes" for above question, would you modify "CC BY-NC-SA 3.0" in FiletToDataURL.mxml to "MIT License" and send me the update FiletToDataURL.mxml?

Thanks,
usitaka

**Comment by Aymkdn** [comment]
Hi,

License updated to MIT License and the file is on Github directly: https://github.com/Aymkdn/FileToDataURI/blob/master/FileToDataURI.mxml

Cheers

**Comment by usitaka** [comment]
Hi, 
I am grateful for your immediate response.
