### ISSUE TITLE
About file name

### ISSUE THREAD

**Issue by aembre** [Aymkdn/FileToDataURI#8]
hello!
How can I get the file name after the file has been readed?
thanks!

**Comment by Aymkdn** [comment]
if you check the example on http://aymkdn.github.io/FileToDataURI/ you'll see : 
`file = files[0]; // in `file` you have the file properties like "name" and "size"`

**Comment by aembre** [comment]
well。Thans a lot!
I use IE8 and go this method.
"swfobject.embedSWF("dist/FileToDataURI.swf", "file-object", "80px", "23px", "10", "dist/swfobject/expressInstall.swf", {}, {}, {});"
Then how can I get the file name?

**Comment by Aymkdn** [comment]
I'm not sure you can. I think I remember that I tried getting this in the past, but I wasn't able to.

**Comment by Aymkdn** [comment]
You'll have to customize the `FileToDataURI.mxml` file (as explained [here](https://github.com/Aymkdn/FileToDataURI/blob/master/README.md)) and search by yourself how you could get the filename. But I'm pretty sure it's complicated and not reliable.

**Comment by aembre** [comment]
Well! I will try!
Anyway,thanks a lot

**Comment by Aymkdn** [comment]
Let me know if you discover anything interesting :-)
